# Funding and Support

# Contact for commercial support and enterprise licensing
custom: ['https://nddev.tech', 'mailto:business@nddev.tech']

# Telegram community
# Join @DevsOpenNetwork for community discussions
